all: ex3q1 ex3q2a ex3q2b ex3q3a ex3q3b

ex3q1: ex3q1.c
	gcc -Wall -ggdb3 -o ex3q1 ex3q1.c

ex3q2a: ex3q2a.c
	gcc -Wall -ggdb3 -o ex3q2a ex3q2a.c

ex3q2b: ex3q2b.c
	gcc -Wall -ggdb3 -o ex3q2b ex3q2b.c

ex3q3a: ex3q3a.c
	gcc -Wall -ggdb3 -o ex3q3a ex3q3a.c

ex3q3b: ex3q3b.c
	gcc -Wall -ggdb3 -o ex3q3b ex3q3b.c